---
title: "Limpieza de datos de la Junta CyL con R"
author: "Luis Javier Samaniego Miguélez"
date: "12-11-2017"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r entorno,eval=TRUE,echo=TRUE,warning=FALSE, message=FALSE}

## Creamos el directorio de trabajo

setwd("C:/Users/Javier/Desktop")

# Vemos la lista de trabajo
  
ls()

# Limpiamos la lista de trabajo

rm(list=ls())

# Comprobamos el directorio de trabajo y descargamos el dataset en la carpeta datos

getwd()
if(!file.exists("./datos")) {dir.create("./datos")}
fileUrl <- "http://www.datosabiertos.jcyl.es/web/jcyl/risp/es/empleo/ofertas-empleo/1284354353012.csv"
download.file(fileUrl, destfile="./datos/ofertas.csv",method="auto")
fechaDescarga <- date()
```

```{r messydataset,eval=TRUE,echo=TRUE,warning=FALSE, message=FALSE}

# Cargamos el messy dataset sin la primera columna

messyempleo <- file("./datos/ofertas.csv","r")
ofertas <- read.csv2(messyempleo,skip=1,skipNul = FALSE)
View(ofertas)

# Ponemos las fechas en el formato correcto

ofertas$Fecha.de.publicación <- as.character(ofertas$Fecha.de.publicación)
ofertas$Fecha.de.publicación <- as.Date(ofertas$Fecha.de.publicación,"%Y%m%d")
ofertas$ultimaActualizacion <- as.character.Date(ofertas$ultimaActualizacion)
ofertas$ultimaActualizacion <- as.Date(ofertas$ultimaActualizacion,"%Y%m%d")

# Reordenamos alfabeticamente toda la tabla según provincia

View(ofertas)
ofertas <- ofertas[order(ofertas$Provincia),]

# Eliminamos las columnas vacias (X y DocumentosAsociados)

library("gdata", lib.loc="~/R/win-library/3.4")
ofertas <- remove.vars(ofertas, c("X"))
ofertas <- remove.vars(ofertas, c("DocumentosAsociados"))
```

```{r tidydataset,eval=TRUE,echo=TRUE,warning=FALSE, message=FALSE}

# Creamos un dataset mas claro y lo llamamos tidy_empleo

Tidy_empleo <- ofertas
View(Tidy_empleo)

# limpiamos la columna decripción quitando los caracteres raros

Tidy_empleo$Descripción <- tolower(gsub("<strong>","", Tidy_empleo$Descripción ))
Tidy_empleo$Descripción <- tolower(gsub("</strong>","", Tidy_empleo$Descripción ))
Tidy_empleo$Descripción <- tolower(gsub("<em>","", Tidy_empleo$Descripción ))
Tidy_empleo$Descripción <- tolower(gsub("</em>","", Tidy_empleo$Descripción ))
Tidy_empleo$Descripción <- tolower(gsub("<p>","", Tidy_empleo$Descripción ))
Tidy_empleo$Descripción <- tolower(gsub("<p/>","", Tidy_empleo$Descripción ))
Tidy_empleo$Descripción <- tolower(gsub("<br />","", Tidy_empleo$Descripción ))
Tidy_empleo$Descripción <- tolower(gsub("</span>","", Tidy_empleo$Descripción ))
Tidy_empleo$Descripción <- tolower(gsub("</ul>","", Tidy_empleo$Descripción ))
Tidy_empleo$Descripción <- tolower(gsub("<ul>","", Tidy_empleo$Descripción ))
Tidy_empleo$Descripción <- tolower(gsub("</li>","", Tidy_empleo$Descripción ))
Tidy_empleo$Descripción <- tolower(gsub("<li>","", Tidy_empleo$Descripción))
Tidy_empleo$Descripción <- tolower(gsub("</a>","", Tidy_empleo$Descripción))

```

```{r resultado,eval=TRUE,echo=TRUE,warning=FALSE, message=FALSE}

# Creamos una carpeta para los datos limpios

if(!file.exists("datos_limpios")){dir.create("datos_limpios")}

# Guardamos en una carpeta nueva y vemos el resultado final

write.csv(Tidy_empleo, file = 'datos_limpios/Tidy_empleo.csv')
View(Tidy_empleo)
```
